export const surpriseMePrompts = [
  "A floating island with a small cottage and a garden",
  "A surreal landscape where the sky is made of colorful patterns",
  "A whimsical tea party with fantastical creatures",
  "A futuristic garden with bioluminescent plants",
  "A steampunk-inspired clock tower with intricate gears",
  "A magical treehouse in the canopy of a giant tree",
  "An ancient dragon resting atop a snowy mountain",
  "A cosmic scene with planets and stars forming a giant face",
  "A cyberpunk street scene with holographic advertisements",
  "A fairy tale castle in a land of giant mushrooms",
  "A dreamlike landscape where the ground is made of clouds",
  "A post-apocalyptic city overgrown with nature",
  "A space station orbiting a vibrant, colorful nebula",
  "A mythical creature emerging from a glowing portal",
  "A retro-futuristic diner with robots as waitstaff",
  "A hidden village inside a giant, hollowed-out tree",
  "A floating market with vendors selling exotic, glowing goods",
  "A whimsical hot air balloon festival in a fantasy world",
  "A serene underwater city inhabited by mermaids",
];
